# Overrides to enable python-tool-assisted generations across pipelines.

stages:
  filter_problems:
    problem_field: null
    diversity_prompts_path: /nemo_run/code/recipes/opensciencereasoning/sdg_pipeline/prompt/diversity_prompts/mcq_various_formats.jsonl
    diversity_prompts_prompt_key: user_prompt
    diversity_prompts_answer_regex_key: output_regex
  generate_solutions:
    prompt_config: ++prompt_config=/nemo_run/code/recipes/opensciencereasoning/sdg_pipeline/prompt/configs/default_problem.yaml
    generation_kwargs:
      args:
        input_file: ${base_output_dir}/solution-sdg/step-0-filter-problems/final_result.jsonl
    dependencies:
      - filter_problems
  decontaminate:
    enabled: False
  topics_labeling:
    enabled: False
  profiling:
    enabled: False
  aggregate:
    enabled: False
  filter_solutions:
    input_file: ${base_output_dir}/solution-sdg/step-4-generate-solutions/final_result.jsonl
    dependencies:
      - generate_solutions
