FROM nvcr.io/nvidia/pytorch:25.04-py3

# Set working directory
WORKDIR /opt

# Install megatron-lm
ENV MEGATRON_COMMIT=dfc0a3d004391a82d8d8a5a6d991b65eaed0190c
RUN git clone https://github.com/NVIDIA/Megatron-LM && \
    cd Megatron-LM && \
    git checkout $MEGATRON_COMMIT && \
    pip install -e .

# installing libs for hf -> megatron conversion
RUN pip install transformers accelerate

# fix for https://github.com/NVIDIA/NeMo/issues/12836
# there is a global requirements lock that we need to remove..
RUN rm /etc/pip/constraint.txt && touch /etc/pip/constraint.txt
RUN pip install -U "nvidia-modelopt[all]>=0.27"

ENV PYTHONPATH=/opt/Megatron-LM
