# using ubuntu instead of debian for easier apptainer installation on arm64
FROM ubuntu:22.04

# Install Python and other dependencies
RUN apt-get update && \
    apt-get install -y \
    python3.10 \
    python3-pip \
    curl \
    wget \
    git \
    git-lfs && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools

# Update package lists and install apptainer for arm64
# https://apptainer.org/docs/admin/1.1/installation.html
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository -y ppa:apptainer/ppa && \
    apt update && apt -y install apptainer && \
    add-apt-repository -y ppa:apptainer/ppa && \
    apt update && apt install -y apptainer-suid && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

# for ifeval benchmark
# TODO: can we get just a single dir?
RUN mkdir /opt/benchmarks
RUN git clone https://github.com/google-research/google-research.git /opt/benchmarks/google-research --depth=1

RUN git clone https://github.com/ShishirPatil/gorilla.git /opt/gorilla
RUN cd /opt/gorilla && git checkout 86d0374d0db52623c5092a73f82c22b87b7e9a25
RUN cd /opt/gorilla/berkeley-function-call-leaderboard && pip install --no-cache-dir -e . --extra-index-url https://download.pytorch.org/whl/cpu

RUN apt remove -y python3-blinker

# ifbench
ARG IFBENCH_COMMIT=c6767a19bd82ac0536cab950f2f8f6bcc6fabe7c
ARG IFBENCH_REPO=https://github.com/allenai/IFBench.git
ARG IFBENCH_DIR=/opt/benchmarks/IFBench
RUN git init "$IFBENCH_DIR" && cd "$IFBENCH_DIR" && git remote add origin "$IFBENCH_REPO" && \
    git fetch --depth 1 origin "${IFBENCH_COMMIT}" && git reset --hard FETCH_HEAD
RUN cd ${IFBENCH_DIR} && pip install -r requirements.txt

# removing on-the-fly installation in ifbench to avoid conflicts from parallel jobs
COPY dockerfiles/ifbench.patch /opt/benchmarks/IFBench/ifbench.patch
RUN cd /opt/benchmarks/IFBench && git apply ifbench.patch

RUN pip install langdetect absl-py immutabledict nltk ipython && \
    python -c "import nltk; from spacy.cli import download; nltk.download('punkt'); nltk.download('punkt_tab'); \
    nltk.download('stopwords'); nltk.download('averaged_perceptron_tagger_eng'); download('en_core_web_sm')"

# we aren't copying main nemo_skills folder as it will always be mounted from host
# but we do want to install all requirements in the container directly
RUN mkdir -p /opt/NeMo-Skills/requirements
COPY pyproject.toml README.md /opt/NeMo-Skills/
COPY requirements /opt/NeMo-Skills/requirements/
# installing sdp in container only
RUN pip install git+https://github.com/NVIDIA/NeMo-speech-data-processor@29b9b1ec0ceaf3ffa441c1d01297371b3f8e11d2
ARG CACHEBUST=1
RUN pip install --no-cache-dir -r /opt/NeMo-Skills/requirements/main.txt
# Fix http mismatch between lepton and dggs by manually downloading dggs here
RUN pip install ddgs
