# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

open_science_mcq_four_options = [
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "intermediate",
        "question": "Let S = \\{a, b, c\\}. How many subsets does S have?\nA: 2\nB: 8\nC: 4\nD: 6",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "complex",
        "question": "Given the set \( S = \\{1, 2, 3, 4, 5\\} \), how many subsets of \( S \) contain both 1 and 4 and have a sum of elements less than 10?\n"
        "A: 3\n"
        "B: 2\n"
        "C: 4\n"
        "D: 5",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "hard",
        "question": "Let S = \\{a, b, c, d, e\\}. How many subsets of S contain at least two elements and include the element a?\n"
        "A: 16\n"
        "B: 24\n"
        "C: 31\n"
        "D: 15",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "brutal",
        "question": "For the set S = \\{1, 2, 3, 4, 5, 6, 7\\}, how many subsets exist such that no two elements in the subset are consecutive numbers?\n"
        "A: 34\n"
        "B: 21\n"
        "C: 44\n"
        "D: 50",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "borderline unsolvable",
        "question": "Let S be an infinite set. Which of the following statements about the cardinality of its power set "
        "\\( \\mathcal{P}(S) \\) is always true?\n"
        "A: \\( |\\mathcal{P}(S)| = \\aleph_{1} \\)\n"
        "B: \\( |\\mathcal{P}(S)| = 2^{|S|} \\)\n"
        "C: \\( |\\mathcal{P}(S)| = |S|^{2} \\)\n"
        "D: None of the above",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "intermediate",
        "question": "Which of the following sets, under the usual operations of addition and multiplication, does **not** form a ring?\n"
        "A: The set of integers, \( \\mathbb{Z} \\)\n"
        "B: The set of real numbers, \( \\mathbb{R} \\)\n"
        "C: The set of rational numbers, \( \\mathbb{Q} \\)\n"
        "D: The set of natural numbers, \( \\mathbb{N} \\)",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "complex",
        "question": "Let \( R \) be a ring, and let \( R^\\times \) denote the set of all units (invertible elements) in \( R \). Which of the following statements is always true for any ring \( R \)?\n"
        "A: \( R^\\times \) is a group under multiplication\n"
        "B: \( R^\\times \) is a subgroup of \( (R, +) \\)\n"
        "C: \( R^\\times \) is a field\n"
        "D: None of the above",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "hard",
        "question": "Let \( F \) be a field, and let \( R = F[x]/(x^2) \) be the quotient ring of the polynomial ring \( F[x] \) modulo the ideal generated by \( x^2 \). Which of the following statements is true about \( R \)?\n"
        "A: \( R \) is an integral domain\n"
        "B: \( R \) is isomorphic to \( F \\times F \\)\n"
        "C: Every element of \( R \) is a unit\n"
        "D: \( R \) is a local ring",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "brutal",
        "question": "Let \( F \) be a field of characteristic zero, and let \( f(x) = x^4 - 2 \in F[x] \). Let \( K \) be the splitting field of \( f(x) \) over \( F \). Which of the following statements is true about the Galois group \( \\text{Gal}(K/F) \\)?\n"
        "A: \( \\text{Gal}(K/F) \\) is isomorphic to the cyclic group \( C_4 \\)\n"
        "B: \( \\text{Gal}(K/F) \\) is isomorphic to the dihedral group \( D_4 \\)\n"
        "C: \( \\text{Gal}(K/F) \\) is isomorphic to the symmetric group \( S_4 \\)\n"
        "D: \( \\text{Gal}(K/F) \\) is isomorphic to the Klein four-group \( V_4 \\)",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "borderline unsolvable",
        "question": "Consider all finite commutative rings with unity (identity element) of order 16. Which of the following statements is true about the number of isomorphism classes of such rings?\n"
        "A: There are exactly 4 isomorphism classes\n"
        "B: There are exactly 5 isomorphism classes\n"
        "C: There are exactly 6 isomorphism classes\n"
        "D: It is impossible to determine without further information",
    },
]

open_science_mcq_ten_options = [
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "intermediate",
        "question": "Let S = \\{a, b, c\\}. How many subsets does S have?\n"
        "A: 3\n"
        "B: 4\n"
        "C: 6\n"
        "D: 7\n"
        "E: 8\n"
        "F: 9\n"
        "G: 10\n"
        "H: 11\n"
        "I: 12\n"
        "J: 13",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "complex",
        "question": "Given the set \( S = \\{1, 2, 3, 4, 5\\} \), how many subsets of \( S \) contain both 1 and 4 and have a sum of elements less than 10?\n"
        "A: 1\n"
        "B: 2\n"
        "C: 3\n"
        "D: 4\n"
        "E: 5\n"
        "F: 6\n"
        "G: 7\n"
        "H: 8\n"
        "I: 9\n"
        "J: 10",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "hard",
        "question": "Let S = \\{a, b, c, d, e\\}. How many subsets of S contain at least two elements and include the element a?\n"
        "A: 15\n"
        "B: 16\n"
        "C: 26\n"
        "D: 30\n"
        "E: 31\n"
        "F: 32\n"
        "G: 48\n"
        "H: 50\n"
        "I: 52\n"
        "J: 60",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "brutal",
        "question": "For the set S = \\{1, 2, 3, 4, 5, 6, 7\\}, how many subsets exist such that no two elements in the subset are consecutive numbers?\n"
        "A: 21\n"
        "B: 29\n"
        "C: 34\n"
        "D: 44\n"
        "E: 50\n"
        "F: 60\n"
        "G: 64\n"
        "H: 70\n"
        "I: 76\n"
        "J: 80",
    },
    {
        "topic": "math",
        "subtopic": "power_sets",
        "difficulty": "borderline unsolvable",
        "question": "Let S be an infinite set. Which of the following statements about the cardinality of its power set "
        "\\( \\mathcal{P}(S) \\) is always true?\n"
        "A: \\( |\\mathcal{P}(S)| = |S| \\)\n"
        "B: \\( |\\mathcal{P}(S)| = 2^{|S|} \\)\n"
        "C: \\( |\\mathcal{P}(S)| = |S|^{2} \\)\n"
        "D: \\( |\\mathcal{P}(S)| = \\aleph_{0} \\)\n"
        "E: \\( |\\mathcal{P}(S)| > \\aleph_{1} \\)\n"
        "F: \\( |\\mathcal{P}(S)| = |\\mathcal{P}(\\mathcal{P}(S))| \\)\n"
        "G: \\( |\\mathcal{P}(S)| = |\\mathbb{R}| \\)\n"
        "H: \\( |\\mathcal{P}(S)| = \\aleph_{1} \\)\n"
        "I: \\( |\\mathcal{P}(S)| = |S|^{|S|} \\)\n"
        "J: None of the above",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "intermediate",
        "question": "Which of the following sets, under the usual operations of addition and multiplication, does **not** form a ring?\n"
        "A: The set of integers, \( \\mathbb{Z} \\)\n"
        "B: The set of real numbers, \( \\mathbb{R} \\)\n"
        "C: The set of natural numbers, \( \\mathbb{N} \\)\n"
        "D: The set of all \( n \\times n \) matrices over \( \\mathbb{R} \\)\n"
        "E: The set of polynomials with real coefficients\n"
        "F: The set of rational numbers, \( \\mathbb{Q} \\)\n"
        "G: The set of complex numbers, \( \\mathbb{C} \\)\n"
        "H: The set of integers modulo \( n \), \( \\mathbb{Z}_n \\)\n"
        "I: The set of even integers\n"
        "J: The set of continuous functions from \( \\mathbb{R} \\) to \( \\mathbb{R} \\)",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "complex",
        "question": "Let \( R \) be a ring, and let \( R^\\times \) denote the set of all units (invertible elements) in \( R \). Which of the following statements is always true for any ring \( R \)?\n"
        "A: \( R^\\times \) is a subring of \( R \\)\n"
        "B: \( R^\\times \) is a subgroup of \( (R, +) \\)\n"
        "C: \( R^\\times \) is a group under multiplication\n"
        "D: \( R^\\times \) is a field\n"
        "E: \( R^\\times \) contains all non-zero elements of \( R \\)\n"
        "F: \( R^\\times \) equals \( R \\) if and only if \( R \) is a field\n"
        "G: \( R^\\times \) is closed under addition\n"
        "H: \( R^\\times \) is empty\n"
        "I: \( R^\\times \) is the center of \( R \\)\n"
        "J: None of the above",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "hard",
        "question": "Let \( F \) be a field, and let \( R = F[x]/(x^2) \) be the quotient ring of the polynomial ring \( F[x] \) modulo the ideal generated by \( x^2 \). Which of the following statements is true about \( R \)?\n"
        "A: \( R \) is an integral domain\n"
        "B: \( R \) is isomorphic to \( F \\times F \\)\n"
        "C: Every element of \( R \) is a unit\n"
        "D: \( R \) is a finite field\n"
        "E: \( R \) has zero divisors\n"
        "F: \( R \) is a local ring\n"
        "G: \( R \) is a field\n"
        "H: \( R \) is isomorphic to \( F \\oplus F \\)\n"
        "I: \( R \) is a principal ideal domain\n"
        "J: \( R \) is isomorphic to \( F[x] \\)",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "brutal",
        "question": "Let \( F \) be a field of characteristic zero, and let \( f(x) = x^4 - 2 \in F[x] \). Let \( K \) be the splitting field of \( f(x) \) over \( F \). Which of the following statements is true about the Galois group \( \\text{Gal}(K/F) \\)?\n"
        "A: \( \\text{Gal}(K/F) \\) is isomorphic to the cyclic group \( C_4 \\)\n"
        "B: \( \\text{Gal}(K/F) \\) is isomorphic to the Klein four-group \( V_4 \\)\n"
        "C: \( \\text{Gal}(K/F) \\) is isomorphic to the symmetric group \( S_4 \\)\n"
        "D: \( \\text{Gal}(K/F) \\) is isomorphic to the dihedral group \( D_4 \\)\n"
        "E: \( \\text{Gal}(K/F) \\) is trivial\n"
        "F: \( \\text{Gal}(K/F) \\) is abelian of order 8\n"
        "G: \( \\text{Gal}(K/F) \\) is non-abelian of order 8\n"
        "H: \( \\text{Gal}(K/F) \\) is isomorphic to \( S_3 \\)\n"
        "I: \( \\text{Gal}(K/F) \\) has order 2\n"
        "J: \( \\text{Gal}(K/F) \\) is isomorphic to \( C_2 \\times C_2 \\times C_2 \\)",
    },
    {
        "topic": "math",
        "subtopic": "rings_and_fields",
        "difficulty": "borderline unsolvable",
        "question": "Consider all finite commutative rings with unity (identity element) of order 16. Which of the following statements is true about the number of isomorphism classes of such rings?\n"
        "A: There are exactly 4 isomorphism classes\n"
        "B: There are exactly 5 isomorphism classes\n"
        "C: There are exactly 6 isomorphism classes\n"
        "D: There are exactly 7 isomorphism classes\n"
        "E: There are exactly 8 isomorphism classes\n"
        "F: There are infinitely many isomorphism classes\n"
        "G: There is only one isomorphism class\n"
        "H: There are exactly 9 isomorphism classes\n"
        "I: There are exactly 10 isomorphism classes\n"
        "J: It is impossible to determine without further information",
    },
]

open_science_aug_similar = [
    {
        "question": "As of 2017, how many of the world's 1-year-old children today have been vaccinated against some disease?A: 30%\nB: 50%\nC: 10%\nD: 20%\nE: 70%\nF: 90%\nG: 40%\nH: 60%\nI: 80%\nJ: 100%",
        "augmented_question": "As of 2020, what percentage of the world's population had access to clean drinking water? A: 30%\nB: 50%\nC: 10%\nD: 20%\nE: 70%\nF: 90%\nG: 40%\nH: 60%\nI: 80%\nJ: 100%",
    },
    {
        "question": "Which of the following is the body cavity that contains the pituitary gland?A: Ventral\nB: Dorsal\nC: Buccal\nD: Thoracic\nE: Pericardial\nF: Abdominal\nG: Spinal\nH: Pelvic\nI: Pleural\nJ: Cranial",
        "augmented_question": "Which of the following is the organ responsible for filtering blood and producing urine? A: Liver\nB: Kidney\nC: Pancreas\nD: Stomach\nE: Heart\nF: Spleen\nG: Gallbladder\nH: Small Intestine\nI: Appendix\nJ: Lungs",
    },
    {
        "question": "In contrast to _______, _______ aim to reward favourable behaviour by companies. The success of such campaigns have been heightened through the use of ___________, which allow campaigns to facilitate the company in achieving _________.A: Boycotts, Buyalls, Blockchain technology, Increased Sales\nB: Buycotts, Boycotts, Digital technology, Decreased Sales\nC: Boycotts, Buycotts, Digital technology, Decreased Sales\nD: Buycotts, Boycotts, Blockchain technology, Charitable donations\nE: Boycotts, Buyalls, Blockchain technology, Charitable donations\nF: Boycotts, Buycotts, Digital technology, Increased Sales\nG: Buycotts, Boycotts, Digital technology, Increased Sales\nH: Boycotts, Buycotts, Physical technology, Increased Sales\nI: Buycotts, Buyalls, Blockchain technology, Charitable donations\nJ: Boycotts, Buycotts, Blockchain technology, Decreased Sales",
        "augmented_question": "In contrast to _______, _______ encourage companies to adopt environmentally friendly practices. The success of these efforts is amplified through the use of ___________, helping companies achieve _________.A: Boycotts, Buyalls, Blockchain technology, Increased Sustainability\nB: Buycotts, Boycotts, Digital technology, Reduced Profits\nC: Boycotts, Buycotts, Blockchain technology, Increased Sales\nD: Buycotts, Boycotts, Digital technology, Charitable Outcomes\nE: Boycotts, Buyalls, Blockchain technology, Improved Compliance\nF: Boycotts, Buycotts, Digital technology, Increased Sustainability\nG: Buycotts, Boycotts, Blockchain technology, Increased Awareness\nH: Buycotts, Boycotts, Digital technology, Enhanced Transparency\nI: Buycotts, Buyalls, Blockchain technology, Increased Donations\nJ: Boycotts, Buycotts, Blockchain technology, Reduced Impact",
    },
    {
        "question": "Predict the number of lines in the EPR spectrum of a solution of 13C-labelled methyl radical (13CH3•), assuming the lines do not overlap.A: 10\nB: 8\nC: 4\nD: 20\nE: 12\nF: 3\nG: 16\nH: 5\nI: 24\nJ: 6",
        "augmented_question": "Predict the number of signals in the proton NMR spectrum of acetone (CH3COCH3), assuming no signal overlap.A: 1\nB: 2\nC: 3\nD: 4\nE: 5\nF: 6\nG: 7\nH: 8\nI: 9\nJ: 10",
    },
    {
        "question": "A tank initially contains a salt solution of 3 grams of salt dissolved in 100 liters of water. A salt solution containing 0.02 grams of salt per liter of water is sprayed into the tank at a rate of 4 liters per minute. The sprayed solution is continually mixed with the salt solution in the tank, and the mixture flows out of the tank at a rate of 4 liters per minute. If the mixing is instantaneous, how many grams of salt are in the tank after 100 minutes have elapsed?A: 3 + e^-2\nB: 2 - e^-4\nC: 2 - e^-2\nD: 3 + e^-4\nE: 2 + e^-3\nF: 2 - e^-3\nG: 3 - e^-2\nH: 2 + e^-2\nI: 2 + e^-4\nJ: 2",
        "augmented_question": "A tank initially contains a sugar solution of 4 grams of sugar dissolved in 200 liters of water. A sugar solution containing 0.01 grams of sugar per liter of water is pumped into the tank at a rate of 5 liters per minute. The solution is perfectly mixed, and the mixture flows out of the tank at the same rate. How many grams of sugar are in the tank after 150 minutes?A: 4 + e^-3\nB: 3 - e^-5\nC: 3 - e^-3\nD: 4 + e^-5\nE: 3 + e^-2\nF: 3 - e^-2\nG: 4 - e^-3\nH: 3 + e^-3\nI: 3 + e^-5\nJ: 3",
    },
]

open_science_aug = [
    {
        "question": "As of 2017, how many of the world's 1-year-old children today have been vaccinated against some disease?A: 30%\nB: 50%\nC: 10%\nD: 20%\nE: 70%\nF: 90%\nG: 40%\nH: 60%\nI: 80%\nJ: 100%",
        "augmented_question": "What is the estimated percentage of the world's population that lives in urban areas as of 2021? A: 30%\nB: 50%\nC: 10%\nD: 20%\nE: 70%\nF: 90%\nG: 40%\nH: 60%\nI: 80%\nJ: 100%",
    },
    {
        "question": "Which of the following is the body cavity that contains the pituitary gland?A: Ventral\nB: Dorsal\nC: Buccal\nD: Thoracic\nE: Pericardial\nF: Abdominal\nG: Spinal\nH: Pelvic\nI: Pleural\nJ: Cranial",
        "augmented_question": "Which of the following regions of the brain is primarily responsible for motor control? A: Medulla\nB: Cerebrum\nC: Hypothalamus\nD: Cerebellum\nE: Pons\nF: Thalamus\nG: Amygdala\nH: Hippocampus\nI: Corpus Callosum\nJ: Pituitary",
    },
    {
        "question": "In contrast to _______, _______ aim to reward favourable behaviour by companies. The success of such campaigns have been heightened through the use of ___________, which allow campaigns to facilitate the company in achieving _________.A: Boycotts, Buyalls, Blockchain technology, Increased Sales\nB: Buycotts, Boycotts, Digital technology, Decreased Sales\nC: Boycotts, Buycotts, Digital technology, Decreased Sales\nD: Buycotts, Boycotts, Blockchain technology, Charitable donations\nE: Boycotts, Buyalls, Blockchain technology, Charitable donations\nF: Boycotts, Buycotts, Digital technology, Increased Sales\nG: Buycotts, Boycotts, Digital technology, Increased Sales\nH: Boycotts, Buycotts, Physical technology, Increased Sales\nI: Buycotts, Buyalls, Blockchain technology, Charitable donations\nJ: Boycotts, Buycotts, Blockchain technology, Decreased Sales",
        "augmented_question": "To promote responsible environmental practices, _______ campaigns encourage consumers to reduce waste. Success is often enhanced by ___________ to increase participation and achieve _________.A: Subsidies, Digital platforms, Increased Recycling\nB: Fines, Blockchain solutions, Decreased Pollution\nC: Incentives, Social media, Higher Engagement\nD: Regulations, Mobile apps, Reduced Waste\nE: Penalties, Online platforms, Improved Awareness\nF: Rewards, Public campaigns, Better Compliance\nG: Penalties, Community drives, Lower Costs\nH: Incentives, Blockchain technology, Increased Accountability\nI: Subsidies, Education programs, Higher Trust\nJ: Rewards, Mobile apps, Reduced Emissions",
    },
    {
        "question": "Predict the number of lines in the EPR spectrum of a solution of 13C-labelled methyl radical (13CH3•), assuming the lines do not overlap.A: 10\nB: 8\nC: 4\nD: 20\nE: 12\nF: 3\nG: 16\nH: 5\nI: 24\nJ: 6",
        "augmented_question": "Determine the number of unique peaks in the IR spectrum of water (H2O) corresponding to molecular vibrations. A: 2\nB: 3\nC: 4\nD: 5\nE: 6\nF: 7\nG: 8\nH: 9\nI: 10\nJ: 11",
    },
    {
        "question": "A tank initially contains a salt solution of 3 grams of salt dissolved in 100 liters of water. A salt solution containing 0.02 grams of salt per liter of water is sprayed into the tank at a rate of 4 liters per minute. The sprayed solution is continually mixed with the salt solution in the tank, and the mixture flows out of the tank at a rate of 4 liters per minute. If the mixing is instantaneous, how many grams of salt are in the tank after 100 minutes have elapsed?A: 3 + e^-2\nB: 2 - e^-4\nC: 2 - e^-2\nD: 3 + e^-4\nE: 2 + e^-3\nF: 2 - e^-3\nG: 3 - e^-2\nH: 2 + e^-2\nI: 2 + e^-4\nJ: 2",
        "augmented_question": "A container initially holds 10 liters of water at 20°C. Water at 80°C is added at a rate of 2 liters per minute, while the mixture is continuously stirred and flows out at the same rate. Assuming perfect mixing, what is the temperature of the water in the container after 60 minutes? A: 30°C\nB: 40°C\nC: 50°C\nD: 60°C\nE: 70°C\nF: 80°C\nG: 90°C\nH: 100°C\nI: 25°C\nJ: 35°C",
    },
]

examples_map = {
    "open_science_mcq_four_options": open_science_mcq_four_options,
    "open_science_mcq_ten_options": open_science_mcq_ten_options,
    "open_science_aug_similar": open_science_aug_similar,
    "open_science_aug": open_science_aug,
}
